# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---
name: build


on:  # yamllint disable-line rule:truthy
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'CrossStream/crossstream'
      # - id: tag
      #   run: echo "tag=$(git describe --tags --always)" >> $GITHUB_OUTPUT
      # - id: contents
      #   run: >
      #      echo ${{ steps.log.outputs.tag }}
      #      > ${{ github.event.repository.name }}.txt
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     # note you'll typically need to create a personal access token
      #     # with permissions to create releases in the other repo
      #     token: ${{ secrets.GH_ZWAVE_ACCESS_TOKEN }}
      #     files: "*.txt"
      - name: build
        run: docker build --tag "${{ github.event.repository.name }}:latest" .
      - name: Upload container image
        # yamllint disable-line rule:line-length
        uses: ishworkh/container-image-artifact-upload@5d71a2417f0576fa11fe770fb04ece58c4587714  # v2.0.0
        with:
          image: "${{ github.event.repository.name }}:latest"
          retention_days: 10
      
