# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---
name: release-action
on: [push]
permissions:
  contents: write
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'CrossStream/crossstream'
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - id: log
        run: echo "tag=$(git describe --tags --always)" >> $GITHUB_OUTPUT 
      - id: exclude
        run: echo '* export-ignore' > .gitattribute
      - id: contents
        run: >
           echo ${{ steps.log.outputs.tag }}
           > ${{ github.event.repository.name }}-${{ steps.log.outputs.tag }}.txt
      - id: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: 'CrossStream/crossstream'
        run: >
          gh release create --prerelease
          ${{ steps.log.outputs.tag }}
          ${{ github.event.repository.name }}-${{ steps.log.outputs.tag }}.txt
          -R ${{ env.repository }}

