# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---
name: release-action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'CrossStream/crossstream'
      - id: tag
        run: echo "tag=$(git describe --tags --always)" >> $GITHUB_OUTPUT
      - id: contents
        run: >
           echo ${{ steps.log.outputs.tag }}
           > ${{ github.event.repository.name }}.txt
      - id: release
        env:
          repository: ${{ github.repository }}-wip
          GH_TOKEN: ${{ secrets.GH_ZWAVE_ACCESS_TOKEN }}
          file: ${{ github.event.repository.name }}.txt

        run: >
          gh release create --prerelease
          ${{ steps.tag.outputs.tag }}
          ${{ env.file }}
          -R ${{ env.repository }}
