# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---
name: release-action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'CrossStream/crossstream'
      - id: log
        run: echo "tag=$(git describe --tags --always)" >> $GITHUB_OUTPUT
      - id: contents
        run: >
           echo ${{ steps.log.outputs.tag }}
           > ${{ github.event.repository.name }}.txt
      - id: release
        env:
          repository: ${{ github.repository }}-wip
          GH_TOKEN: ${{ secrets.ZWAVE_PERSONAL_ACCESS_TOKEN }}
        run: >
          cat ${{ github.event.repository.name }}.txt ;
          gh release create --prerelease
          ${{ steps.log.outputs.tag }}
          ${{ github.event.repository.name }}.txt
          -R ${{ env.repository }}
