# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---
name: test

# yamllint disable-line rule:line-length
run-name: "test: ${{ github.event.workflow_run.head_branch }}#${{ github.event.workflow_run.head_commit.id }}"

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows: ["build"]
    types:
      - completed
    permissions:
      contents: read      
      statuses: write
# https://github.com/orgs/community/discussions/58868
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download image
        id: image
        # yamllint disable-line rule:line-length
        uses: ishworkh/container-image-artifact-download@ccb3671db007622e886a2d7037eb62b119d5ffaf  # v2.0.0
        with:
          image: "${{ github.event.repository.name }}:latest"
          workflow: "build"
          token: ${{ secrets.GH_SL_ACCESS_TOKEN }}
          workflow_run_id: ${{ github.event.workflow_run.id }}
          path: ${{ runner.temp }}/artifacts/
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'CrossStream/crossstream'
          ref: ${{ github.event.workflow_run.head_commit.id }}

      # - name: release-downloader
      #   uses: robinraju/release-downloader@v1.12
      #   with:
      #     repository: crossstream/crossstream
      #     fileName: '*.txt'
      #     latest: true
      # - name: zw-downloader
      #   uses: robinraju/release-downloader@v1.12
      #   with:
      #     repository: 'Z-Wave-Alliance/z-wave-stack-binaries'
      #     fileName: 'z-wave-stack-binaries-*-Linux.tar.gz'
      #     token: ${{ secrets.GH_ZWAVE_ACCESS_TOKEN }}
      #     latest: true
      - name: run
        id: run
        run: ./run.sh
        continue-on-error: true
        
      - name: Report
        uses: actions/github-script@v7
        if: always()
        env:
          status: ${{ steps.run.outcome }}
          sha: ${{ github.event.workflow_run.head_commit.id }}
        with:
          github-token: ${{ secrets.GH_CROSSSTREAM_ACCESS_TOKEN }}
          script: |
            await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: process.env.sha,
            state: process.env.status
            });
            process.exit(process.env.status == 'success' ? 0 : 1);
 
