# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---

name: test

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows: ["release-action"]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: release-downloader
        uses: robinraju/release-downloader@v1.12
        with:
          repository: crossstream/crossstream
          fileName: "*.txt"
