# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---

name: test

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows: ["release-action"]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: release-downloader
        uses: robinraju/release-downloader@v1.12
        with:
          repository: crossstream/crossstream
          fileName: '*.txt'
      - name: zw-downloader
        uses: robinraju/release-downloader@v1.12
        with:
          repository: 'Z-Wave-Alliance/z-wave-stack-binaries'
          fileName: 'z-wave-stack-binaries-25.1.0-25-g3b1e09d-Linux.tar.gz'
          token: GH_ZWAVE_ACCESS_TOKEN
